ball_fcnn_debug: false  # only active when true and vision/debug is true, too!
ball_fcnn_model_path: '/models/fcnn031'
ball_fcnn_threshold: .9  # minimal value for a candidate to be considered
ball_fcnn_expand_stepsize: 4
ball_fcnn_pointcloud_stepsize: 10
ball_fcnn_shuffle_candidate_list: false  # shuffles the list of possible candidate points
ball_fcnn_min_ball_diameter: 15
ball_fcnn_max_ball_diameter: 150
ball_fcnn_publish_output: false
ball_fcnn_publish_field_boundary_offset: 5

field_color_detector_path: '/config/color_spaces/GO2019_interpolated.txt'
field_color_detector_path_sim: '/config/color_spaces/GO2019_interpolated.txt'
field_color_detector_use_hsv_green: false
field_color_detector_hsv_lower_values_h: 46
field_color_detector_hsv_lower_values_s: 101
field_color_detector_hsv_lower_values_v: 12
field_color_detector_hsv_upper_values_h: 98
field_color_detector_hsv_upper_values_s: 255
field_color_detector_hsv_upper_values_v: 255

white_color_detector_lower_values_h: 70
white_color_detector_lower_values_s: 90
white_color_detector_lower_values_v: 120
white_color_detector_upper_values_h: 100
white_color_detector_upper_values_s: 140
white_color_detector_upper_values_v: 255

red_color_detector_lower_values_h: 139
red_color_detector_lower_values_s: 50
red_color_detector_lower_values_v: 0
red_color_detector_upper_values_h: 255
red_color_detector_upper_values_s: 255
red_color_detector_upper_values_v: 255

blue_color_detector_lower_values_h: 90
blue_color_detector_lower_values_s: 197
blue_color_detector_lower_values_v: 134
blue_color_detector_upper_values_h: 116
blue_color_detector_upper_values_s: 255
blue_color_detector_upper_values_v: 255

field_boundary_finder_vertical_steps: 30
field_boundary_finder_horizontal_steps: 30
field_boundary_finder_roi_height: 11
field_boundary_finder_roi_width: 5
field_boundary_finder_precision_pix: 5
field_boundary_finder_min_precision_pix: 3

vision_ball_classifier: 'fcnn'  # cascade, fcnn or dummy
vision_debug_image: false
vision_publish_debug_image: false
vision_publish_field_mask_image: false
vision_parallelize: true
vision_use_sim_color: false
vision_ball_candidate_field_boundary_y_offset: 0
vision_ball_candidate_rating_threshold: 0.5
vision_debug_printer_classes: ''

line_detector_field_boundary_offset: 15
line_detector_linepoints_range: 10000
line_detector_blur_kernel_size: 9

obstacle_color_threshold: 10
obstacle_white_threshold: 12
obstacle_field_boundary_diff_threshold: 20
obstacle_candidate_field_boundary_offset: 30
obstacle_candidate_min_width: 30
obstacle_finder_step_length: 5

goalpost_expand_stepsize: 5
goalpost_white_threshold: 100

ROS_img_msg_topic: 'image_raw'
ROS_img_queue_size: 1
ROS_ball_msg_topic: 'ball_in_image'
ROS_fcnn_img_msg_topic: 'fcnn_image'
ROS_obstacle_msg_topic: 'obstacles_in_image'
ROS_goal_msg_topic: 'goal_in_image'
ROS_line_msg_topic: 'line_in_image'
ROS_dynamic_color_space_msg_topic: 'dynamic_color_space'
ROS_debug_image_msg_topic: 'debug_image'
ROS_field_mask_image_msg_topic: 'field_mask'
ROS_dynamic_color_space_field_mask_image_msg_topic: 'dynamic_field_mask'

ball_finder_classify_threshold: 0.5
ball_finder_scale_factor: 1.1
ball_finder_min_neighbors: 1
ball_finder_min_size: 10

classifier_model_path: '/models/classifier_01'

cascade_classifier_path: '/classifier/cascadeNew.xml'

dynamic_color_space_active: true
dynamic_color_space_publish_field_mask_image: false
dynamic_color_space_queue_max_size: 10
dynamic_color_space_threshold: 0.8
dynamic_color_space_kernel_radius: 1
