#color_test_params:
debug_printer_classes: 'color_tester'

#field_color_detector:
path: '/config/testfield_color01.yaml'

lower_values_h: 70
lower_values_s: 90
lower_values_v: 120
upper_values_h: 100
upper_values_s: 140
upper_values_v: 255

# Subscriber
img_msg_topic: 'image_raw'
img_queue_size: 1

color_tester_mask_image: 'color_tester_mask'
